{{- define "dictaphone.audioExtractor.deployment" -}}
{{- $root := index . 0 -}}
{{- $mode := index . 1 -}}
{{- $config := $root.Values.celeryAudioExtractor -}}
{{- $modeVarsKey := printf "%sEnvVars" $mode -}}
{{- $modeReplicasKey := printf "%sReplicas" $mode -}}
{{- $envVars := mergeOverwrite (deepCopy (default dict $config.envVars)) (deepCopy (default dict (index $config $modeVarsKey))) (dict "AUDIO_EXTRACTOR_MODE" $mode) -}}
{{- $env := include "dictaphone.env.transformDict" $envVars -}}
{{- $fullName := printf "%s-%s" (include "dictaphone.audioExtractor.fullname" $root) $mode | trunc 63 | trimSuffix "-" -}}
{{- $component := printf "audio-worker-%s" $mode -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  annotations:
     {{- with $config.dpAnnotations }}
     {{- toYaml . | nindent 4 }}
     {{- end }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "dictaphone.common.labels" (list $root $component) | nindent 4 }}
spec:
  replicas: {{ index $config $modeReplicasKey }}
  selector:
    matchLabels:
      {{- include "dictaphone.common.selectorLabels" (list $root $component) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with $config.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "dictaphone.common.selectorLabels" (list $root $component) | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
      {{- if $root.Values.image.credentials }}
      imagePullSecrets:
        - name: {{ include "dictaphone.secret.dockerconfigjson.name" (dict "fullname" (include "dictaphone.fullname" $root) "imageCredentials" $root.Values.image.credentials) }}
      {{- end }}
      shareProcessNamespace: {{ $config.shareProcessNamespace }}
      containers:
        {{- with $config.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ $root.Chart.Name }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          imagePullPolicy: {{ $config.image.pullPolicy }}
          {{- with $config.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- $env | nindent 12 }}
          {{- with $config.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: work
              mountPath: /work
            {{- range $index, $value := $root.Values.mountFiles }}
            - name: "files-{{ $index }}"
              mountPath: {{ $value.path }}
              subPath: content
            {{- end }}
            {{- range $name, $volume := $config.persistence }}
            - name: "{{ $name }}"
              mountPath: "{{ $volume.mountPath }}"
            {{- end }}
            {{- range $config.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath | default "" }}
              readOnly: {{ .readOnly }}
            {{- end }}
      {{- with $config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $config.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $config.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: work
          emptyDir:
            sizeLimit: 4Gi
        {{- range $index, $value := $root.Values.mountFiles }}
        - name: "files-{{ $index }}"
          configMap:
            name: "{{ include "dictaphone.fullname" $root }}-files-{{ $index }}"
        {{- end }}
        {{- range $name, $volume := $config.persistence }}
        - name: "{{ $name }}"
          {{- if eq $volume.type "emptyDir" }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: "{{ $fullName }}-{{ $name }}"
          {{- end }}
        {{- end }}
        {{- range $config.extraVolumes }}
        - name: {{ .name }}
          {{- if .existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
          {{- else if .hostPath }}
          hostPath:
            {{ toYaml .hostPath | nindent 12 }}
          {{- else if .csi }}
          csi:
            {{- toYaml .csi | nindent 12 }}
          {{- else if .configMap }}
          configMap:
            {{- toYaml .configMap | nindent 12 }}
          {{- else if .emptyDir }}
          emptyDir:
            {{- toYaml .emptyDir | nindent 12 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
{{- if $config.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}
  namespace: {{ $root.Release.Namespace | quote }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "dictaphone.common.selectorLabels" (list $root $component) | nindent 6 }}
{{- end }}
{{- end }}
{{ include "dictaphone.audioExtractor.deployment" (list . "transcoding") }}
{{ include "dictaphone.audioExtractor.deployment" (list . "validation") }}
