"""
Core application enums declaration
"""

from django.conf import global_settings, settings
from django.utils.translation import gettext_lazy as _

UUID_REGEX = (
    r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
)
FILE_EXT_REGEX = r"[a-zA-Z0-9]{1,10}"

# Django sets `LANGUAGES` by default with all supported languages. We can use it for
# the choice of languages which should not be limited to the few languages active in
# the app.
# pylint: disable=no-member
ALL_LANGUAGES = getattr(
    settings,
    "ALL_LANGUAGES",
    [(language, _(name)) for language, name in global_settings.LANGUAGES],
)


ISO_639_1_CHOICES = (
    ("ab", "ab"),
    ("aa", "aa"),
    ("af", "af"),
    ("ak", "ak"),
    ("sq", "sq"),
    ("am", "am"),
    ("ar", "ar"),
    ("an", "an"),
    ("hy", "hy"),
    ("as", "as"),
    ("av", "av"),
    ("ae", "ae"),
    ("ay", "ay"),
    ("az", "az"),
    ("bm", "bm"),
    ("ba", "ba"),
    ("eu", "eu"),
    ("be", "be"),
    ("bn", "bn"),
    ("bh", "bh"),
    ("bi", "bi"),
    ("bs", "bs"),
    ("br", "br"),
    ("bg", "bg"),
    ("my", "my"),
    ("ca", "ca"),
    ("ch", "ch"),
    ("ce", "ce"),
    ("ny", "ny"),
    ("zh", "zh"),
    ("cv", "cv"),
    ("kw", "kw"),
    ("co", "co"),
    ("cr", "cr"),
    ("hr", "hr"),
    ("cs", "cs"),
    ("da", "da"),
    ("dv", "dv"),
    ("nl", "nl"),
    ("dz", "dz"),
    ("en", "en"),
    ("eo", "eo"),
    ("et", "et"),
    ("ee", "ee"),
    ("fo", "fo"),
    ("fj", "fj"),
    ("fi", "fi"),
    ("fr", "fr"),
    ("ff", "ff"),
    ("gl", "gl"),
    ("ka", "ka"),
    ("de", "de"),
    ("el", "el"),
    ("gn", "gn"),
    ("gu", "gu"),
    ("ht", "ht"),
    ("ha", "ha"),
    ("he", "he"),
    ("hz", "hz"),
    ("hi", "hi"),
    ("ho", "ho"),
    ("hu", "hu"),
    ("ia", "ia"),
    ("id", "id"),
    ("ie", "ie"),
    ("ga", "ga"),
    ("ig", "ig"),
    ("ik", "ik"),
    ("io", "io"),
    ("is", "is"),
    ("it", "it"),
    ("iu", "iu"),
    ("ja", "ja"),
    ("jv", "jv"),
    ("kl", "kl"),
    ("kn", "kn"),
    ("kr", "kr"),
    ("ks", "ks"),
    ("kk", "kk"),
    ("km", "km"),
    ("ki", "ki"),
    ("rw", "rw"),
    ("ky", "ky"),
    ("kv", "kv"),
    ("kg", "kg"),
    ("ko", "ko"),
    ("ku", "ku"),
    ("kj", "kj"),
    ("la", "la"),
    ("lb", "lb"),
    ("lg", "lg"),
    ("li", "li"),
    ("ln", "ln"),
    ("lo", "lo"),
    ("lt", "lt"),
    ("lu", "lu"),
    ("lv", "lv"),
    ("gv", "gv"),
    ("mk", "mk"),
    ("mg", "mg"),
    ("ms", "ms"),
    ("ml", "ml"),
    ("mt", "mt"),
    ("mi", "mi"),
    ("mr", "mr"),
    ("mh", "mh"),
    ("mn", "mn"),
    ("na", "na"),
    ("nv", "nv"),
    ("nd", "nd"),
    ("ne", "ne"),
    ("ng", "ng"),
    ("nb", "nb"),
    ("nn", "nn"),
    ("no", "no"),
    ("ii", "ii"),
    ("nr", "nr"),
    ("oc", "oc"),
    ("oj", "oj"),
    ("cu", "cu"),
    ("om", "om"),
    ("or", "or"),
    ("os", "os"),
    ("pa", "pa"),
    ("pi", "pi"),
    ("fa", "fa"),
    ("pl", "pl"),
    ("ps", "ps"),
    ("pt", "pt"),
    ("qu", "qu"),
    ("rm", "rm"),
    ("rn", "rn"),
    ("ro", "ro"),
    ("ru", "ru"),
    ("sa", "sa"),
    ("sc", "sc"),
    ("sd", "sd"),
    ("se", "se"),
    ("sm", "sm"),
    ("sg", "sg"),
    ("sr", "sr"),
    ("gd", "gd"),
    ("sn", "sn"),
    ("si", "si"),
    ("sk", "sk"),
    ("sl", "sl"),
    ("so", "so"),
    ("st", "st"),
    ("es", "es"),
    ("su", "su"),
    ("sw", "sw"),
    ("ss", "ss"),
    ("sv", "sv"),
    ("ta", "ta"),
    ("te", "te"),
    ("tg", "tg"),
    ("th", "th"),
    ("ti", "ti"),
    ("bo", "bo"),
    ("tk", "tk"),
    ("tl", "tl"),
    ("tn", "tn"),
    ("to", "to"),
    ("tr", "tr"),
    ("ts", "ts"),
    ("tt", "tt"),
    ("tw", "tw"),
    ("ty", "ty"),
    ("ug", "ug"),
    ("uk", "uk"),
    ("ur", "ur"),
    ("uz", "uz"),
    ("ve", "ve"),
    ("vi", "vi"),
    ("vo", "vo"),
    ("wa", "wa"),
    ("cy", "cy"),
    ("wo", "wo"),
    ("fy", "fy"),
    ("xh", "xh"),
    ("yi", "yi"),
    ("yo", "yo"),
    ("za", "za"),
    ("zu", "zu"),
)
