import { ApiFileItem } from '@/features/files/api/types'

export const mockedFiles: ApiFileItem[] = [
  {
    id: 's1',
    created_at: '2026-04-28T09:30:00Z',
    updated_at: '2026-04-28T10:05:00Z',
    title: 'Point équipe',
    type: 'audio_recording',
    creator: { id: 'u1', full_name: 'Claire Martin', short_name: 'CM' },
    deleted_at: null,
    hard_deleted_at: null,
    filename: 'point-equipe-2026-04-28.m4a',
    upload_state: 'ready',
    mimetype: 'audio/m4a',
    size: 22000000,
    description: 'Synchronisation quotidienne de l’équipe',
    duration_seconds: 1800,
    ai_jobs: [
      {
        id: 'job-s1',
        type: 'transcript',
        status: 'success',
        created_at: '2026-04-28T09:30:05Z',
        updated_at: '2026-04-28T10:04:30Z',
        docs_app_id: 'doc-s1',
      },
    ],
    abilities: {
      destroy: true,
      partial_update: true,
      restore: false,
      hard_delete: false,
    },
    url: 'https://example.com/audio/point-equipe.m4a',
  },
  {
    id: 's2',
    created_at: '2026-04-27T14:00:00Z',
    updated_at: '2026-04-27T15:10:00Z',
    title: 'Réunion hebdo',
    type: 'audio_recording',
    creator: { id: 'u2', full_name: 'Julien Petit', short_name: 'JP' },
    deleted_at: null,
    hard_deleted_at: null,
    filename: 'reunion-hebdo.m4a',
    upload_state: 'ready',
    mimetype: 'audio/m4a',
    size: 48000000,
    description: 'Suivi hebdomadaire des projets',
    duration_seconds: 3600,
    ai_jobs: [
      {
        id: 'job-s2',
        type: 'transcript',
        status: 'success',
        created_at: '2026-04-27T14:00:05Z',
        updated_at: '2026-04-27T15:09:40Z',
        docs_app_id: 'doc-s2',
      },
    ],
    abilities: {
      destroy: true,
      partial_update: true,
      restore: false,
      hard_delete: false,
    },
    url: 'https://example.com/audio/reunion-hebdo.m4a',
  },
  {
    id: 's3',
    created_at: '2026-04-28T14:00:00Z',
    updated_at: '2026-04-28T14:12:00Z',
    title: 'Aujourd’hui 14:00',
    type: 'audio_recording',
    creator: { id: 'u3', full_name: 'Sophie Leroy', short_name: 'SL' },
    deleted_at: null,
    hard_deleted_at: null,
    filename: '2026-04-28-14h00.m4a',
    upload_state: 'pending',
    mimetype: 'audio/m4a',
    size: 8000000,
    description: 'Réunion en cours de traitement',
    duration_seconds: 720,
    ai_jobs: [
      {
        id: null,
        type: 'transcript',
        status: 'pending',
        created_at: '2026-04-28T14:00:10Z',
        updated_at: '2026-04-28T14:00:10Z',
        docs_app_id: null,
      },
    ],
    abilities: {
      destroy: true,
      partial_update: false,
      restore: false,
      hard_delete: false,
    },
    policy: 'upload-policy',
    url: null,
  },
  {
    id: 's4',
    created_at: '2026-04-26T11:00:00Z',
    updated_at: '2026-04-26T11:25:00Z',
    title: 'Décisions clés',
    type: 'audio_recording',
    creator: { id: 'u4', full_name: 'Thomas Bernard', short_name: 'TB' },
    deleted_at: null,
    hard_deleted_at: null,
    filename: 'decisions-cles.m4a',
    upload_state: 'ready',
    mimetype: 'audio/m4a',
    size: 15000000,
    description: 'Réunion axée sur les arbitrages',
    duration_seconds: 1500,
    ai_jobs: [
      {
        id: 'job-s4',
        type: 'transcript',
        status: 'success',
        created_at: '2026-04-26T11:00:05Z',
        updated_at: '2026-04-26T11:24:40Z',
        docs_app_id: 'doc-s4',
      },
    ],
    abilities: {
      destroy: true,
      partial_update: true,
      restore: false,
      hard_delete: false,
    },
    url: 'https://example.com/audio/decisions-cles.m4a',
  },
  {
    id: 's5',
    created_at: '2026-04-25T16:45:00Z',
    updated_at: '2026-04-25T16:50:00Z',
    title: 'Point rapide',
    type: 'audio_recording',
    creator: { id: 'u1', full_name: 'Claire Martin', short_name: 'CM' },
    deleted_at: null,
    hard_deleted_at: null,
    filename: 'point-rapide.m4a',
    upload_state: 'ready',
    mimetype: 'audio/m4a',
    size: 3000000,
    description: 'Décision rapide sur une priorité',
    duration_seconds: 240,
    ai_jobs: [
      {
        id: 'job-s5',
        type: 'transcript',
        status: 'success',
        created_at: '2026-04-25T16:45:05Z',
        updated_at: '2026-04-25T16:49:30Z',
        docs_app_id: 'doc-s5',
      },
    ],
    abilities: {
      destroy: true,
      partial_update: true,
      restore: false,
      hard_delete: false,
    },
    url: 'https://example.com/audio/point-rapide.m4a',
  },
  {
    id: 's6',
    created_at: '2026-04-24T10:00:00Z',
    updated_at: '2026-04-24T11:10:00Z',
    title: 'Lancement projet',
    type: 'audio_recording',
    creator: { id: 'u2', full_name: 'Julien Petit', short_name: 'JP' },
    deleted_at: null,
    hard_deleted_at: null,
    filename: 'lancement-projet.m4a',
    upload_state: 'ready',
    mimetype: 'audio/m4a',
    size: 52000000,
    description: 'Réunion de démarrage',
    duration_seconds: 3900,
    ai_jobs: [
      {
        id: 'job-s6',
        type: 'transcript',
        status: 'success',
        created_at: '2026-04-24T10:00:05Z',
        updated_at: '2026-04-24T11:09:10Z',
        docs_app_id: 'doc-s6',
      },
    ],
    abilities: {
      destroy: true,
      partial_update: true,
      restore: false,
      hard_delete: false,
    },
    url: 'https://example.com/audio/lancement-projet.m4a',
  },
]
