import { WhisperXResponse } from '@/features/ai-jobs/api/types'

export const mockedTranscript: WhisperXResponse = {
  segments: [
    {
      start: 0,
      end: 22,
      speaker: 'SPEAKER_1',
      text: 'Bonjour à toutes et à tous. Merci d’être présents pour ce kick-off du projet Transcripts. L’objectif aujourd’hui est de poser le cadre, valider les priorités et s’assurer que nous sommes alignés sur la première version.',
      words: [],
    },
    {
      start: 22,
      end: 45,
      speaker: 'SPEAKER_1',
      text: 'Pour rappel, l’outil permet d’enregistrer des réunions en présentiel et de générer automatiquement une transcription exploitable dans un document partagé. On va commencer par un tour de table rapide.',
      words: [],
    },
    {
      start: 45,
      end: 70,
      speaker: 'SPEAKER_2',
      text: 'Très bien. Côté produit, on vise une première version simple et robuste : enregistrement, transcription, et restitution dans un document. L’idée est de supprimer totalement la prise de notes manuelle.',
      words: [],
    },
    {
      start: 70,
      end: 95,
      speaker: 'SPEAKER_2',
      text: 'On ne cherche pas encore à faire du résumé automatique dans cette phase. L’enjeu principal est la fiabilité de la transcription et la fluidité de l’expérience utilisateur.',
      words: [],
    },
    {
      start: 95,
      end: 120,
      speaker: 'SPEAKER_3',
      text: 'Sur la partie technique, il faudra être vigilant sur les environnements bruyants et les réunions informelles. On sait que le signal audio peut être très variable selon les usages.',
      words: [],
    },
    {
      start: 120,
      end: 145,
      speaker: 'SPEAKER_3',
      text: 'On va aussi devoir gérer le vocabulaire métier spécifique. Beaucoup de sigles et de termes internes peuvent dégrader la qualité de la transcription si on ne les anticipe pas.',
      words: [],
    },
    {
      start: 145,
      end: 170,
      speaker: 'SPEAKER_4',
      text: 'Est-ce qu’on prévoit un mécanisme pour enrichir le dictionnaire au fil de l’usage ? Ça pourrait être utile pour améliorer progressivement la qualité.',
      words: [],
    },
    {
      start: 170,
      end: 195,
      speaker: 'SPEAKER_3',
      text: 'Oui, exactement. L’idée est de permettre l’ajout de vocabulaire spécifique par équipe ou par service, pour adapter la transcription au contexte réel.',
      words: [],
    },
    {
      start: 195,
      end: 220,
      speaker: 'SPEAKER_1',
      text: 'Très bien. Sur l’usage terrain, il faut aussi qu’on garde en tête les réunions informelles. L’enjeu est que l’enregistrement soit le plus rapide possible.',
      words: [],
    },
    {
      start: 220,
      end: 245,
      speaker: 'SPEAKER_1',
      text: 'Si ça prend trop de temps ou si ça demande trop de configuration, les utilisateurs ne l’utiliseront pas dans les moments spontanés.',
      words: [],
    },
    {
      start: 245,
      end: 270,
      speaker: 'SPEAKER_2',
      text: 'On pourrait aussi penser à un historique clair des enregistrements, avec des titres automatiques simples comme ‘Réunion équipe’ ou ‘Point rapide’.',
      words: [],
    },
    {
      start: 270,
      end: 295,
      speaker: 'SPEAKER_2',
      text: 'L’objectif est que l’utilisateur puisse retrouver une réunion en quelques secondes, sans avoir besoin de se souvenir de la date exacte.',
      words: [],
    },
    {
      start: 295,
      end: 320,
      speaker: 'SPEAKER_4',
      text: 'Sur la partie restitution, même sans résumé, la transcription seule doit déjà permettre de comprendre rapidement ce qui a été dit et décidé.',
      words: [],
    },
    {
      start: 320,
      end: 345,
      speaker: 'SPEAKER_4',
      text: 'C’est important pour les personnes absentes ou pour celles qui doivent reprendre un sujet après coup.',
      words: [],
    },
    {
      start: 345,
      end: 370,
      speaker: 'SPEAKER_1',
      text: 'Parfait. On valide donc le périmètre pour cette première version : enregistrement, transcription et restitution dans un document exploitable.',
      words: [],
    },
    {
      start: 370,
      end: 395,
      speaker: 'SPEAKER_1',
      text: 'On se donne rendez-vous la semaine prochaine pour un point d’avancement, avec les premiers retours techniques et produit.',
      words: [],
    },
  ],
  word_segments: [],
}
