# Generated by Django 5.2.12 on 2026-03-27 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_pg_trgm_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiFileJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('remote_job_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('transcript', 'Transcript'), ('summary', 'Summary')], max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=25)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file')),
            ],
            options={
                'verbose_name': 'AiJob',
                'verbose_name_plural': 'AiJobs',
                'db_table': 'ai_job',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['file', 'type', '-created_at'], name='ai_job_file_id_adb047_idx')],
            },
        ),
    ]
