# Generated by Django 5.2.12 on 2026-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aifilejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duration_seconds',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
