# Generated by Django 5.2.12 on 2026-03-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aifilejob',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='core.file'),
        ),
    ]
