# Generated by Django 5.2.12 on 2026-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aifilejob_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aifilejob',
            name='remote_job_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
