# Generated by Django 5.2.12 on 2026-04-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aifilejob_remote_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifilejob',
            name='docs_app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
