# Generated by Django 5.2.12 on 2026-04-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aifilejob_docs_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag_show_mobile_app_popup',
            field=models.BooleanField(default=True, help_text='Whether to show the mobile app popup to the user.', verbose_name='show mobile app popup'),
        ),
    ]
