# Generated by Django 5.2.13 on 2026-05-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aifilejob_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('web_recording', 'Web recording'), ('web_file_upload', 'Web file upload'), ('mobile_recording', 'Mobile recording'), ('mobile_file_upload', 'Mobile file upload')], default='unknown', max_length=25),
        ),
    ]
