# Generated by Django 5.2.14 on 2026-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_file_upload_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lifecycle_state',
            field=models.CharField(choices=[('active', 'Active'), ('pending_original_data_deletion', 'Pending original data deletion'), ('original_data_deleted', 'Original data deleted'), ('pending_auto_hard_delete', 'Pending auto hard delete')], default='active', max_length=30),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['-created_at'], name='file_created_915352_idx'),
        ),
    ]
