# Generated by Django 5.2.15 on 2026-08-10 09:37

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    dependencies = [("core", "0013_file_language")]

    operations = [
        migrations.AddField(
            model_name="file",
            name="original_file_data_delete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="original_file_data_delete_at_with_grace_period",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="file_auto_hard_delete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="file_auto_hard_delete_at_with_grace_period",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="storage_bucket_name",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="trashbin_purge_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="trashbin_purge_at_with_grace_period",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["storage_bucket_name", "created_at"],
                name="file_bucket_created_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["storage_bucket_name", "deleted_at"],
                name="file_bucket_deleted_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["original_file_data_delete_at"],
                name="file_original_delete_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["original_file_data_delete_at_with_grace_period"],
                name="file_original_delete_grace_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_auto_hard_delete_at"],
                name="file_hard_delete_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_auto_hard_delete_at_with_grace_period"],
                name="file_hard_delete_grace_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["trashbin_purge_at"],
                name="file_trashbin_purge_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["trashbin_purge_at_with_grace_period"],
                name="file_trashbin_purge_grace_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=(
                    (
                        Q(storage_bucket_name__isnull=True)
                        & Q(original_file_data_delete_at__isnull=True)
                        & Q(original_file_data_delete_at_with_grace_period__isnull=True)
                        & Q(file_auto_hard_delete_at__isnull=True)
                        & Q(file_auto_hard_delete_at_with_grace_period__isnull=True)
                    )
                    | (
                        Q(storage_bucket_name__isnull=False)
                        & Q(original_file_data_delete_at__isnull=False)
                        & Q(original_file_data_delete_at_with_grace_period__isnull=False)
                        & Q(file_auto_hard_delete_at__isnull=False)
                        & Q(file_auto_hard_delete_at_with_grace_period__isnull=False)
                    )
                ),
                name="file_snapshot_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=(
                    Q(trashbin_purge_at__isnull=True)
                    & Q(trashbin_purge_at_with_grace_period__isnull=True)
                )
                | (
                    Q(trashbin_purge_at__isnull=False)
                    & Q(trashbin_purge_at_with_grace_period__isnull=False)
                ),
                name="file_trashbin_deadlines",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=(
                    (
                        Q(original_file_data_delete_at__isnull=True)
                        & Q(original_file_data_delete_at_with_grace_period__isnull=True)
                    )
                    | Q(
                        original_file_data_delete_at__lte=F(
                            "original_file_data_delete_at_with_grace_period"
                        )
                    )
                ),
                name="file_original_deadline_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=(
                    (
                        Q(file_auto_hard_delete_at__isnull=True)
                        & Q(file_auto_hard_delete_at_with_grace_period__isnull=True)
                    )
                    | Q(
                        file_auto_hard_delete_at__lte=F(
                            "file_auto_hard_delete_at_with_grace_period"
                        )
                    )
                ),
                name="file_hard_delete_deadline_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=(
                    (
                        Q(trashbin_purge_at__isnull=True)
                        & Q(trashbin_purge_at_with_grace_period__isnull=True)
                    )
                    | Q(
                        trashbin_purge_at__lte=F(
                            "trashbin_purge_at_with_grace_period"
                        )
                    )
                ),
                name="file_trashbin_deadline_order",
            ),
        ),
    ]
