# Generated by Django 5.2.15 on 2026-08-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_file_email_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='audio_extraction_state',
            field=models.CharField(choices=[('pending_audio_extraction', 'Pending audio extraction'), ('extracting_audio', 'Extracting audio'), ('extraction_done', 'Audio extraction done'), ('audio_extraction_failed', 'Audio extraction failed')], default='pending_audio_extraction', max_length=30),
        ),
    ]
