# Generated by Django 5.2.17 on 2026-10-08 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_audio_jobs(apps, schema_editor):
    """Reference legacy objects in place; never access object storage here."""
    File = apps.get_model("core", "File")
    AudioJob = apps.get_model("core", "AudioJob")
    AiFileJob = apps.get_model("core", "AiFileJob")
    db = schema_editor.connection.alias
    for file in File.objects.using(db).iterator(chunk_size=500):
        done = file.audio_extraction_state == "extraction_done"
        failed = file.audio_extraction_state == "audio_extraction_failed"
        job_id = uuid.uuid4()
        job = AudioJob.objects.using(db).create(
            id=job_id, file_id=file.pk, mode="transcoding",
            extraction_id=uuid.uuid4(),
            status="success" if done else "failed" if failed else "pending",
            duration_seconds=file.duration_seconds if done else None,
            output_key=(f"{settings.FILE_UPLOAD_PATH}/{file.pk}.audio.ogg" if done
                        else f"{settings.FILE_UPLOAD_PATH}/{file.pk}/audio/{job_id}.ogg"),
            metadata={"migrated": True},
        )
        if done:
            validation = AudioJob.objects.using(db).create(
                file_id=file.pk, mode="validation", status="success",
                extraction_id=job.extraction_id, source_job_id=job.pk,
                metadata={"migrated": True},
            )
            AiFileJob.objects.using(db).filter(file_id=file.pk, type="transcript").update(
                validated_audio_job_id=validation.pk
            )


def restore_file_states(apps, schema_editor):
    """Restore the inferred value when rolling the schema back."""
    File = apps.get_model("core", "File")
    AudioJob = apps.get_model("core", "AudioJob")
    db = schema_editor.connection.alias
    for file in File.objects.using(db).iterator(chunk_size=500):
        job = AudioJob.objects.using(db).filter(file_id=file.pk).order_by("-created_at", "-id").first()
        state = "pending_audio_extraction"
        if job and job.status == "processing":
            state = "extracting_audio"
        elif job and job.status in {"failed", "stale"}:
            state = "audio_extraction_failed"
        elif job and job.status == "success" and job.mode == "validation":
            state = "extraction_done"
        File.objects.using(db).filter(pk=file.pk).update(audio_extraction_state=state)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aifilejob_docs_creation_in_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('extraction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('mode', models.CharField(choices=[('transcoding', 'Transcoding'), ('validation', 'Validation')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('stale', 'Stale')], default='pending', max_length=12)),
                ('attempt_number', models.PositiveIntegerField(default=0)),
                ('output_key', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_jobs', to='core.file')),
                ('retry_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry', to='core.audiojob')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='core.audiojob')),
            ],
            options={
                'db_table': 'audio_job',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='aifilejob',
            name='validated_audio_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to='core.audiojob'),
        ),
        migrations.AddIndex(
            model_name='audiojob',
            index=models.Index(fields=['file', '-created_at', '-id'], name='audio_job_file_id_87324c_idx'),
        ),
        migrations.AddIndex(
            model_name='audiojob',
            index=models.Index(fields=['mode', 'status', 'created_at'], name='audio_job_mode_5b1dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='audiojob',
            index=models.Index(fields=['status', 'expires_at'], name='audio_job_status_c4b1c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiojob',
            constraint=models.UniqueConstraint(fields=('extraction_id', 'mode', 'attempt_number'), name='audio_job_unique_attempt'),
        ),
        migrations.RunPython(backfill_audio_jobs, restore_file_states),
        migrations.RemoveField(model_name="file", name="audio_extraction_state"),
    ]
