name: Download Crowdin translations

on:
  workflow_dispatch:

permissions: {}

jobs:
  crowdin:
    permissions:
      contents: write # push the translations branch
      pull-requests: write # open the pull request
    uses: suitenumerique/ci/.github/workflows/_crowdin-download.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      crowdin_config: crowdin/config.yml
      # Sources in crowdin/config.yml are relative to the repository root
      crowdin_base_path: ../
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
