name: Docker Hub Workflow
run-name: Docker Hub Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  build-and-push-backend:
    permissions:
      contents: read
    uses: suitenumerique/ci/.github/workflows/_docker-publish.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      image_name: lasuite/dictaphone-backend
      context: .
      file: Dockerfile
      target: backend-production
      docker_user: "1001:127"
      should_push: ${{ github.event_name != 'pull_request' || startsWith(github.head_ref, 'integration/') }}
      trivy_scan: ${{ vars.TRIVY_SCAN_ENABLED == 'true' }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  build-and-push-audio-extractor:
    permissions:
      contents: read
    uses: suitenumerique/ci/.github/workflows/_docker-publish.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      image_name: lasuite/dictaphone-audio-extractor
      context: .
      file: src/audio-extractor/Dockerfile
      target: audio-extractor-production
      docker_user: "1001:127"
      should_push: ${{ github.event_name != 'pull_request' || startsWith(github.head_ref, 'integration/') }}
      trivy_scan: ${{ vars.TRIVY_SCAN_ENABLED == 'true' }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  build-and-push-frontend-generic:
    permissions:
      contents: read
    uses: suitenumerique/ci/.github/workflows/_docker-publish.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      image_name: lasuite/dictaphone-frontend
      context: .
      file: src/frontend/Dockerfile
      target: frontend-production
      docker_user: "1001:127"
      should_push: ${{ github.event_name != 'pull_request' || startsWith(github.head_ref, 'integration/') }}
      trivy_scan: ${{ vars.TRIVY_SCAN_ENABLED == 'true' }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  build-and-push-frontend-dinum:
    permissions:
      contents: read
    uses: suitenumerique/ci/.github/workflows/_docker-publish.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      image_name: lasuite/dictaphone-frontend-dinum
      context: .
      file: docker/dinum-frontend/Dockerfile
      target: frontend-production
      docker_user: "1001:127"
      should_push: ${{ github.event_name != 'pull_request' || startsWith(github.head_ref, 'integration/') }}
      trivy_scan: ${{ vars.TRIVY_SCAN_ENABLED == 'true' }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  notify-argocd:
    needs:
      - build-and-push-frontend-generic
      - build-and-push-frontend-dinum
      - build-and-push-backend
      - build-and-push-audio-extractor
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions: {}
    steps:
      - name: Notify ArgoCD
        uses: suitenumerique/ci/actions/argocd-webhook-notification@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
        with:
          deployment_repo_path: ${{ secrets.DEPLOYMENT_REPO_URL }}
          argocd_webhook_secret: ${{ secrets.ARGOCD_PREPROD_WEBHOOK_SECRET }}
          argocd_url: ${{ vars.ARGOCD_PREPROD_WEBHOOK_URL }}
